// import css from "./home.module.css"
// import type { Metadata } from "next";
// import Image from "next/image";

// export const metadata: Metadata = {
//   title: "Home",
//   description: "Generated by create next app",
// };

// export default function Home(){
//   return(
// <main>
//   <div className={css.container}>
//     <h1 className={css.title}>Welcome to NoteHub</h1>
//     <p className={css.description}>
//       NoteHub is a simple and efficient application designed for managing
//       personal notes. It helps keep your thoughts organized and accessible
//       in one place, whether you are at home or on the go.
//     </p>
//     <p className={css.description}>
//       The app provides a clean interface for writing, editing, and browsing
//       notes. With support for keyword search and structured organization,
//       NoteHub offers a streamlined experience for anyone who values clarity
//       and productivity.
//     </p>
//     <Image src="/notehub-og-meta.jpg"  alt="test" width={600} height={400}    />
//   </div>
// </main>

//   )
// }



import css from "./home.module.css";
import type { Metadata } from "next";
import Image from "next/image";
import Head from "next/head";

// Статичні мета-теги для всього хому
export const metadata: Metadata = {
  title: "NoteHub",
  description: "NoteHub - A platform to share your notes with the world.",
};

export default function Home() {
  return (
    <>
      {/* Head для OG/Twitter */}
      <Head>
        <title>NoteHub</title>
        <meta
          name="description"
          content="NoteHub - A platform to share your notes with the world."
        />

        {/* Open Graph */}
        <meta property="og:title" content="NoteHub" />
        <meta
          property="og:description"
          content="NoteHub - A platform to share your notes with the world."
        />
        <meta
          property="og:url"
          content="https://08-zustand-p6qvz852v-masikkx.vercel.app/"
        />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="NoteHub" />
        <meta
          property="og:image"
          content="https://08-zustand-p6qvz852v-masikkx.vercel.app/notehub-og-meta.jpg"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />

        {/* Twitter Card */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="NoteHub" />
        <meta
          name="twitter:description"
          content="NoteHub - A platform to share your notes with the world."
        />
        <meta
          name="twitter:image"
          content="https://08-zustand-p6qvz852v-masikkx.vercel.app/notehub-og-meta.jpg"
        />
      </Head>

      <main>
        <div className={css.container}>
          <h1 className={css.title}>Welcome to NoteHub</h1>
          <p className={css.description}>
            NoteHub is a simple and efficient application designed for
            managing personal notes. It helps keep your thoughts organized
            and accessible in one place, whether you are at home or on the go.
          </p>
          <p className={css.description}>
            The app provides a clean interface for writing, editing, and
            browsing notes. With support for keyword search and structured
            organization, NoteHub offers a streamlined experience for anyone
            who values clarity and productivity.
          </p>
          <Image
            src="/notehub-og-meta.jpg"
            alt="NoteHub Preview"
            width={600}
            height={400}
          />
        </div>
      </main>
    </>
  );
}
