import type { Metadata } from "next";
import NoteForm from '@/components/NoteForm/NoteForm';

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
};

const CreateNote = async () => {
  return    <>
      <NoteForm />
    </>
};

export default CreateNote;
